// export const Data = [
//   {
//     id: 1,
//     name: "Jhon Due",
//     city: "London",
//     state: "London",
//     country: "England",
//     category: "Entertainment",
//     type: "A",
//     active: false,
//   },
//   {
//     id: 2,
//     name: "Rajesh",
//     city: "Surat",
//     state: "Gujarat",
//     country: "India",
//     category: "Engineering",
//     type: "B",
//     active: true,
//   },
//   {
//     id: 3,
//     name: "Jay",
//     city: "Mumbai",
//     state: "Maharashtra",
//     country: "India",
//     category: "Business",
//     type: "A",
//     active: true,
//   },
//   {
//     id: 4,
//     name: "Mohan",
//     city: "Hyderabad",
//     state: "Telangana",
//     country: "India",
//     category: "Health",
//     type: "B",
//     active: true,
//   },
//   {
//     id: 5,
//     name: "Yash",
//     city: "Pune",
//     state: "Maharashtra",
//     country: "India",
//     category: "Education",
//     type: "C",
//     active: true,
//   },
// ];

// export const Data = [
//   {
//     id: 1,
//     name: "foo",
//     city: "dallas",
//     category: "one",
//     type: "A",
//     active: "FALSE",
//   },
//   {
//     id: 2,
//     name: "bar",
//     city: "dallas",
//     category: "one",
//     type: "B",
//     active: "FALSE",
//   },
//   {
//     id: 3,
//     name: "jim",
//     city: "san francisco",
//     category: "one",
//     type: "B",
//     active: "TRUE",
//   },
//   {
//     id: 4,
//     name: "jane",
//     city: "denver",
//     category: "two",
//     type: "C",
//     active: "FALSE",
//   },
// ];
export const Data = [
  {
    id: 1,
    mall: "V R mall",
    address: "Surat",
    rating: "A",
  },
  {
    id: 2,
    mall: "Rahul Raj Mall",
    address: "dallas",
    rating: "B",
  },
  {
    id: 3,
    mall: "Raj Imperial",
    address: "san francisco",
    category: "one",
    rating: "B",
  },
  {
    id: 4,
    mall: "jane",
    address: "denver",
    category: "two",
    rating: "C",
  },
];
